CREATE DATABASE IF NOT EXISTS beam;
USE beam;

CREATE TABLE workers (
  id         INT AUTO_INCREMENT UNIQUE,
  worker_id  VARCHAR(255) PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  status     BOOLEAN NOT NULL DEFAULT FALSE
);
