CREATE DATABASE IF NOT EXISTS beam;
USE beam;

CREATE TABLE workers (
  id         INT AUTO_INCREMENT UNIQUE,
  worker_id  VARCHAR(255) PRIMARY KEY,
  ip         VARCHAR(45) NOT NULL,
  port       SMALLINT UNSIGNED NOT NULL,
  hotkey     VARCHAR(255) NOT NULL,
  bandwidth  INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
